version: '3'
services:
  linux:
    image: ubuntu
    stdin_open: true 
    tty: true
    command:
      - bash
      - -c
      - |
        apt-get update
        apt-get install -y net-tools
        tail -f /dev/null
  # win32:
  #   image: mcr.microsoft.com/windows/nanoserver:1803-amd64
  #   command: [ 'tasklist' ]
